language: node_js

node_js:
  - "stable"
cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master

install:
  - "yarn add gatsby --global"
  - "yarn --frozen-lockfile"
script:
  - "yarn run build"
after_success:
  - "yarn run deploy"
