name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install, build, and test
      run: |
        yarn add gatsby --global
        yarn --frozen-lockfile
        yarn run build:prod
      env:
        CI: true
