name: Audit pull request
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      run: sleep 30
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'brunnerlivio.netlify.com'
        url: 'https://brunnerliv.io'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'