name: Lighthouse

on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Netlify preview
        id: preview
        uses: josephduffy/wait-for-netlify-action@v1
        with:
          site_name: brunnerlivio
          max_timeout: 300
      - uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ steps.preview.outputs.url }}
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
