name: Update Data

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install, build, and test
      run: |
        yarn --frozen-lockfile
        yarn run update-data
      env:
        OPENWEATHERMAP_TOKEN: ${{ secrets.OPENWEATHERMAP_TOKEN }}
    - name: Deploy to Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      token: ${{ secrets.TOKEN }}
      gist_id: from_gist_url
      file_path: build/book.pdf
      file_type: binary
